vim.keymap.set("n", "<leader>ff", function()
	require("telescope.builtin").find_files({ hidden = true })
end)
vim.keymap.set("n", "<leader>fg", function()
	require("telescope.builtin").git_files({ hidden = true })
end)
vim.keymap.set("n", "<leader>fw", function()
	require("telescope.builtin").live_grep({ hidden = true })
end)
vim.keymap.set("n", "<leader>fb", function()
	("telescope.builtin").buffers({ hidden = true })
end)
vim.keymap.set("n", "<leader>fh", function()
	require("telescope.builtin").help_tags({ hidden = true })
end)
